import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Belle Martinée Classic Tee',
    description: 'Premium quality unisex t-shirt featuring the Belle Martinée signature logo. Made from 100% organic cotton for ultimate comfort and breathability.',
    price: 35.00,
    currency: 'USD',
    image: '/products/product-1.svg',
    category: 'Tops',
  },
  {
    id: '2',
    name: 'Signature Hoodie',
    description: 'Cozy and stylish hoodie with embroidered Belle Martinée logo. Perfect for casual outings. Features a soft fleece interior and adjustable drawstring hood.',
    price: 65.00,
    currency: 'USD',
    image: '/products/product-2.svg',
    category: 'Tops',
  },
  {
    id: '3',
    name: 'Gold Script Tote Bag',
    description: 'Elegant canvas tote bag with gold script logo. Spacious and durable for everyday use. Made from heavy-duty cotton canvas.',
    price: 28.00,
    currency: 'USD',
    image: '/products/product-3.svg',
    category: 'Accessories',
  },
  {
    id: '4',
    name: 'Belle Martinée Cap',
    description: 'Structured cap with signature gold embroidery. One size fits most. Features an adjustable strap for a perfect fit.',
    price: 32.00,
    currency: 'USD',
    image: '/products/product-4.svg',
    category: 'Accessories',
  },
  {
    id: '5',
    name: 'Script Logo Mug',
    description: '15oz premium ceramic mug with gold Belle Martinée script. Microwave and dishwasher safe. Perfect for your morning coffee or tea.',
    price: 22.00,
    currency: 'USD',
    image: '/products/product-5.svg',
    category: 'Home',
  },
  {
    id: '6',
    name: 'Luxury Sweatshirt',
    description: 'Premium heavyweight sweatshirt in the classic Belle Martinée style. Ultra-soft cotton blend for maximum comfort.',
    price: 55.00,
    currency: 'USD',
    image: '/products/product-6.svg',
    category: 'Tops',
  },
  {
    id: '7',
    name: 'Embroidered Crewneck',
    description: 'Soft cotton crewneck with elegant Belle Martinée embroidery on chest. Classic fit for everyday comfort.',
    price: 48.00,
    currency: 'USD',
    image: '/products/product-7.svg',
    category: 'Tops',
  },
  {
    id: '8',
    name: 'Signature Baseball Tee',
    description: 'Classic baseball tee with contrast sleeves and Belle Martinée logo. Comfortable tri-blend fabric.',
    price: 38.00,
    currency: 'USD',
    image: '/products/product-8.svg',
    category: 'Tops',
  },
];
